local M = {}

---@type mrok.HighlightsFn
function M.get(c)
    -- stylua: ignore
    return {
        ColorColumn  = { bg = c.bg },
        Conceal      = { fg = c.blue, bg = c.bg },
        Conditional  = { fg = c.magenta },
        Cursor       = { fg = c.fg },
        lCursor      = { fg = c.fg, bg = c.fg },
        CursorIM     = { fg = c.fg },
        CursorColumn = { bg = c.bg },
        CursorLine   = { bg = c.bg },
        DiffAdd      = { bg = c.bg_green },
        DiffChange   = { bg = c.bg_magenta },
        DiffText     = { bg = c.bg_magenta },
        DiffDelete   = { bg = c.bg_red },
        Directory    = { fg = c.blue },
        EndOfBuffer  = { fg = c.bg },
        ErrorMsg     = { fg = c.red, bg = c.bg },
        FloatBorder  = { fg = c.gray1, bg = c.bg },
        FoldColumn   = { fg = c.blue, bg = c.bg },
        Folded       = { fg = c.blue, bg = c.bg },
        Ignore       = { fg = c.fg, bg = c.bg },
        IncSearch    = { fg = c.bg, bg = c.green },
        Include      = { fg = c.magenta },
        Label        = { fg = c.red },
        LineNr       = { fg = c.gray2, bg = c.bg },
        Macro        = { fg = c.cyan },
        MatchParen   = { fg = c.blue, bg = c.bg },
        ModeMsg      = { fg = c.fg, bg = c.bg },
        MoreMsg      = { fg = c.magenta },
        MsgArea      = { fg = c.fg, bg = c.bg },
        MsgSeparator = { fg = c.fg, bg = c.bg },
        NonText      = { fg = c.red },
        Normal       = { fg = c.fg, bg = c.bg },
        NormalFloat  = { bg = c.bg },
        NormalNC     = { fg = c.fg, bg = c.bg },
        Pmenu        = { bg = c.bg2 },
        PmenuSel     = { bg = c.bg3 },
        PreCondit    = { fg = c.cyan },
        Question     = { fg = c.magenta },
        QuickFixLine = { bg = c.green },
        Repeat       = { fg = c.magenta },
        Search       = { fg = c.bg, bg = c.green },
        SignColumn   = { fg = c.gray2, bg = c.bg },
        SpellBad     = { fg = c.green },
        SpellCap     = { fg = c.cyan },
        SpellLocal   = { fg = c.blue },
        SpellRare    = { fg = c.cyan },
        Statement    = { fg = c.blue },
        StatusLine   = { fg = c.fg, bg = c.bg3 },
        StatusLineNC = { fg = c.fg, bg = c.bg3 },
        StorageClass = { fg = c.magenta },
        Structure    = { fg = c.blue },
        Substitute   = { fg = c.orange, bg = c.cyan },
        TabLine      = { fg = c.green, bg = c.bg },
        TabLineFill  = { fg = c.fg, bg = c.bg },
        TabLineSel   = { fg = c.fg, bg = c.bg },
        Tag          = { fg = c.blue },
        TermCursor   = { fg = c.fg, bg = c.fg },
        TermCursorNC = { fg = c.fg, bg = c.fg },
        Title        = { fg = c.blue },
        Todo         = { fg = c.red, bg = c.bg },
        VertSplit    = { fg = c.gray1, bg = c.bg },
        WinSeparator = { fg = c.gray1, bg = c.bg },
        Visual       = { bg = c.gray1 },
        VisualNOS    = { bg = c.bg },
        WarningMsg   = { fg = c.orange, bg = c.bg },
        Whitespace   = { fg = c.red },
        WildMenu     = { fg = c.fg, bg = c.blue },
        tutorOK      = { fg = c.green },
        tutorX       = { fg = c.red },
    }
end

return M
